// BtDonchianBreakout: generated by backtest_engine.ninjatrader (https://github.com/paolo993788/Algorithmic-trading).
// Do not edit by hand: regenerate with `python -m backtest_engine.ninjatrader --write scripts/ninjatrader_strategies`.
//
// Channel breakout with an ATR stop (Turtle system 1): buy stop one tick above the highest high of the last EntryPeriod
// bars, sell stop one tick below the lowest low; stop StopAtr ATRs from the fill, then the tighter of that stop and the
// ExitPeriod-bar channel; an opposite breakout reverses the position. Unmanaged approach (both entry stops work at once).
// The rules and defaults are those of backtest_engine.bars.donchian_breakout_plan; the platform's historical fills
// (Calculate.OnBarClose, Standard order fill resolution, entry orders alive for one bar, TimeInForce Gtc) follow the
// model of cpp/bars.hpp, so the trade list of the Strategy Analyzer can be reconciled with the Python backtest by
// backtest_engine.ninjatrader.reconcile_trades. Apply a commission template to the backtest account: commissions are
// not a strategy property. Prices are rounded to the tick grid half away from zero, as in Python.
#region Using declarations
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Xml.Serialization;
using NinjaTrader.Cbi;
using NinjaTrader.Data;
using NinjaTrader.NinjaScript;
using NinjaTrader.NinjaScript.Indicators;
#endregion

namespace NinjaTrader.NinjaScript.Strategies
{
    public class BtDonchianBreakout : Strategy
    {
        private const int MaxContracts = 10000;
        private ATR atr;
        private MAX entryHigh, exitHigh;
        private MIN entryLow, exitLow;
        private Order longEntry, shortEntry, protectiveStop;
        private MarketPosition lastPosition = MarketPosition.Flat;
        private double entryStop = double.NaN;  // protective stop fixed at entry: fill -/+ StopAtr ATR (in ticks)
        private int stopTicks = 1;              // ATR stop distance decided at the close before the entry
        private int contracts = 1;              // contracts of the next entry, decided at the same close

        // The managed approach ignores an entry order in the opposite direction of a working one, so a breakout
        // strategy with a buy stop and a sell stop working at once uses the unmanaged approach: orders are submitted,
        // changed and cancelled explicitly, and live for one bar like the plans of backtest_engine.bars.

        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Description = "Donchian channel breakout with ATR stop and channel trailing exit (backtest_engine)";
                Name = "BtDonchianBreakout";
                Calculate = Calculate.OnBarClose;
                EntriesPerDirection = 1;
                EntryHandling = EntryHandling.AllEntries;
                IsExitOnSessionCloseStrategy = false;
                ExitOnSessionCloseSeconds = 30;
                IsFillLimitOnTouch = false;
                MaximumBarsLookBack = MaximumBarsLookBack.Infinite;
                OrderFillResolution = OrderFillResolution.Standard;
                Slippage = 0;
                IsUnmanaged = true;

                StartBehavior = StartBehavior.WaitUntilFlat;
                TimeInForce = TimeInForce.Gtc;
                TraceOrders = false;
                RealtimeErrorHandling = RealtimeErrorHandling.StopCancelClose;
                StopTargetHandling = StopTargetHandling.PerEntryExecution;
                BarsRequiredToTrade = 20;
                IsInstantiatedOnEachOptimizationIteration = true;
                EntryPeriod = 20;
                ExitPeriod = 10;
                AtrPeriod = 20;
                StopAtr = 2.0;
                Contracts = 1;
                RiskPerTrade = 0.0;
            }
            else if (State == State.Configure)
            {
                BarsRequiredToTrade = Math.Max(EntryPeriod, AtrPeriod);
            }
            else if (State == State.DataLoaded)
            {
                atr = ATR(AtrPeriod);
                entryHigh = MAX(High, EntryPeriod);
                entryLow = MIN(Low, EntryPeriod);
                exitHigh = MAX(High, ExitPeriod);
                exitLow = MIN(Low, ExitPeriod);
            }
        }

        private static bool IsWorking(Order order)
        {
            return order != null && (order.OrderState == OrderState.Working || order.OrderState == OrderState.Accepted
                || order.OrderState == OrderState.Submitted || order.OrderState == OrderState.ChangePending
                || order.OrderState == OrderState.ChangeSubmitted || order.OrderState == OrderState.TriggerPending);
        }

        private void CancelWorking(ref Order order)
        {
            if (IsWorking(order))
                CancelOrder(order);
            order = null;
        }

        protected override void OnBarUpdate()
        {
            if (BarsInProgress != 0)
                return;
            if (Position.MarketPosition != lastPosition)
            {
                // A position opened (or reversed) during this bar: freeze its ATR stop from the previous decision.
                if (Position.MarketPosition == MarketPosition.Long)
                    entryStop = Position.AveragePrice - stopTicks * TickSize;
                else if (Position.MarketPosition == MarketPosition.Short)
                    entryStop = Position.AveragePrice + stopTicks * TickSize;
                lastPosition = Position.MarketPosition;
            }
            // Every order lives for one bar: cancel what is still working, then decide again from this close.
            CancelWorking(ref longEntry);
            CancelWorking(ref shortEntry);
            CancelWorking(ref protectiveStop);
            if (CurrentBar < Math.Max(EntryPeriod, AtrPeriod))
                return;

            double upper = RoundToTick(entryHigh[0]) + TickSize;                                   // buy stop
            double lower = RoundToTick(entryLow[0]) - TickSize;                                    // sell stop
            double longTrail = Math.Min(RoundToTick(exitLow[0]), RoundToTick(Close[0]) - TickSize);   // below the market
            double shortTrail = Math.Max(RoundToTick(exitHigh[0]), RoundToTick(Close[0]) + TickSize); // above the market
            stopTicks = Math.Max(1, (int)Math.Floor(Math.Abs(StopAtr * atr[0] / TickSize) + 0.5 + 1e-9));
            contracts = Contracts;
            if (RiskPerTrade > 0)
                contracts = Math.Max(1, (int)Math.Min(Math.Floor(RiskPerTrade / (stopTicks * TickSize * Instrument.MasterInstrument.PointValue)), MaxContracts));

            if (Position.MarketPosition == MarketPosition.Long)
                protectiveStop = SubmitOrderUnmanaged(0, OrderAction.Sell, OrderType.StopMarket, Position.Quantity, 0, Math.Max(entryStop, longTrail), "", "LongStop");
            else
                longEntry = SubmitOrderUnmanaged(0, OrderAction.Buy, OrderType.StopMarket, contracts + (Position.MarketPosition == MarketPosition.Short ? Position.Quantity : 0), 0, upper, "", "Long");
            if (Position.MarketPosition == MarketPosition.Short)
                protectiveStop = SubmitOrderUnmanaged(0, OrderAction.BuyToCover, OrderType.StopMarket, Position.Quantity, 0, Math.Min(entryStop, shortTrail), "", "ShortStop");
            else
                shortEntry = SubmitOrderUnmanaged(0, OrderAction.SellShort, OrderType.StopMarket, contracts + (Position.MarketPosition == MarketPosition.Long ? Position.Quantity : 0), 0, lower, "", "Short");
        }

        protected override void OnOrderUpdate(Order order, double limitPrice, double stopPrice, int quantity, int filled, double averageFillPrice, OrderState orderState, DateTime time, ErrorCode error, string comment)
        {
            // Keep the latest instance of each order (the platform may replace the object it returned).
            if (order.Name == "Long")
                longEntry = order;
            else if (order.Name == "Short")
                shortEntry = order;
            else if (order.Name == "LongStop" || order.Name == "ShortStop")
                protectiveStop = order;
        }

        protected override void OnExecutionUpdate(Execution execution, string executionId, double price, int quantity, MarketPosition marketPosition, string orderId, DateTime time)
        {
            if (execution.Order == null || execution.Order.OrderState != OrderState.Filled)
                return;
            string name = execution.Order.Name;
            if (name == "LongStop" || name == "ShortStop")
            {
                // Stopped out: a pending reversal order must now open a fresh position of `contracts`.
                protectiveStop = null;
                if (IsWorking(longEntry) && longEntry.Quantity != contracts)
                    ChangeOrder(longEntry, contracts, 0, longEntry.StopPrice);
                if (IsWorking(shortEntry) && shortEntry.Quantity != contracts)
                    ChangeOrder(shortEntry, contracts, 0, shortEntry.StopPrice);
            }
            else if (name == "Long" || name == "Short")
            {
                // A new position or a reversal: the old stop is obsolete; attach the ATR stop from the fill price.
                CancelWorking(ref protectiveStop);
                if (name == "Long")
                    protectiveStop = SubmitOrderUnmanaged(0, OrderAction.Sell, OrderType.StopMarket, contracts, 0, price - stopTicks * TickSize, "", "LongStop");
                else
                    protectiveStop = SubmitOrderUnmanaged(0, OrderAction.BuyToCover, OrderType.StopMarket, contracts, 0, price + stopTicks * TickSize, "", "ShortStop");
            }
        }

        private double RoundToTick(double price)
        {
            return Math.Sign(price) * Math.Floor(Math.Abs(price) / TickSize + 0.5 + 1e-9) * TickSize;
        }

        #region Properties
        [NinjaScriptProperty]
        [Range(1, int.MaxValue)]
        [Display(Name = "Entry period", Description = "Bars of the entry channel", Order = 1, GroupName = "Parameters")]
        public int EntryPeriod { get; set; }

        [NinjaScriptProperty]
        [Range(1, int.MaxValue)]
        [Display(Name = "Exit period", Description = "Bars of the trailing exit channel", Order = 2, GroupName = "Parameters")]
        public int ExitPeriod { get; set; }

        [NinjaScriptProperty]
        [Range(1, int.MaxValue)]
        [Display(Name = "ATR period", Description = "Bars of the average true range", Order = 3, GroupName = "Parameters")]
        public int AtrPeriod { get; set; }

        [NinjaScriptProperty]
        [Range(0.01, double.MaxValue)]
        [Display(Name = "Stop (ATRs)", Description = "Protective stop distance from the fill, in ATRs", Order = 4, GroupName = "Parameters")]
        public double StopAtr { get; set; }

        [NinjaScriptProperty]
        [Range(1, int.MaxValue)]
        [Display(Name = "Contracts", Description = "Contracts per trade when RiskPerTrade is 0", Order = 5, GroupName = "Parameters")]
        public int Contracts { get; set; }

        [NinjaScriptProperty]
        [Range(0, double.MaxValue)]
        [Display(Name = "Risk per trade", Description = "Currency at risk at the stop (0: fixed contracts)", Order = 6, GroupName = "Parameters")]
        public double RiskPerTrade { get; set; }
        #endregion
    }
}
