// BtOpeningRangeBreakout: generated by backtest_engine.ninjatrader (https://github.com/paolo993788/Algorithmic-trading).
// Do not edit by hand: regenerate with `python -m backtest_engine.ninjatrader --write scripts/ninjatrader_strategies`.
//
// Opening range breakout (Zarattini and Aziz, 2023) on intraday bars: at the close of the first bar of the session, buy
// (sell) at the next open when the bar closed above (below) its open, stop at the bar's low (high), target RMultiple
// times the distance from the close to the stop, exit on session close. Apply the session's trading-hours template.
// The rules and defaults are those of backtest_engine.bars.opening_range_breakout_plan; the platform's historical fills
// (Calculate.OnBarClose, Standard order fill resolution, entry orders alive for one bar, TimeInForce Gtc) follow the
// model of cpp/bars.hpp, so the trade list of the Strategy Analyzer can be reconciled with the Python backtest by
// backtest_engine.ninjatrader.reconcile_trades. Apply a commission template to the backtest account: commissions are
// not a strategy property. Prices are rounded to the tick grid half away from zero, as in Python.
#region Using declarations
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Xml.Serialization;
using NinjaTrader.Cbi;
using NinjaTrader.Data;
using NinjaTrader.NinjaScript;
using NinjaTrader.NinjaScript.Indicators;
#endregion

namespace NinjaTrader.NinjaScript.Strategies
{
    public class BtOpeningRangeBreakout : Strategy
    {
        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Description = "Opening range breakout with stop at the first bar's extreme and exit on session close (backtest_engine)";
                Name = "BtOpeningRangeBreakout";
                Calculate = Calculate.OnBarClose;
                EntriesPerDirection = 1;
                EntryHandling = EntryHandling.AllEntries;
                IsExitOnSessionCloseStrategy = true;
                ExitOnSessionCloseSeconds = 30;
                IsFillLimitOnTouch = false;
                MaximumBarsLookBack = MaximumBarsLookBack.Infinite;
                OrderFillResolution = OrderFillResolution.Standard;
                Slippage = 0;

                StartBehavior = StartBehavior.WaitUntilFlat;
                TimeInForce = TimeInForce.Gtc;
                TraceOrders = false;
                RealtimeErrorHandling = RealtimeErrorHandling.StopCancelClose;
                StopTargetHandling = StopTargetHandling.PerEntryExecution;
                BarsRequiredToTrade = 1;
                IsInstantiatedOnEachOptimizationIteration = true;
                RMultiple = 10.0;
                MinRangeTicks = 1;
                Contracts = 1;
                RiskPerTrade = 0.0;
            }
        }

        private const int MaxContracts = 10000;

        protected override void OnBarUpdate()
        {
            if (BarsInProgress != 0 || CurrentBar < 1 || !Bars.IsFirstBarOfSession || Position.MarketPosition != MarketPosition.Flat)
                return;
            if (High[0] - Low[0] < MinRangeTicks * TickSize - 1e-12)
                return;
            double pointValue = Instrument.MasterInstrument.PointValue;
            if (Close[0] > Open[0])
            {
                double stop = RoundToTick(Low[0]);
                double target = RoundToTick(Close[0] + RMultiple * (Close[0] - Low[0]));
                int contracts = Contracts;
                if (RiskPerTrade > 0 && Close[0] - stop > 0)
                    contracts = Math.Max(1, (int)Math.Min(Math.Floor(RiskPerTrade / ((Close[0] - stop) * pointValue)), MaxContracts));
                SetStopLoss("Long", CalculationMode.Price, stop, false);
                SetProfitTarget("Long", CalculationMode.Price, target);
                EnterLong(contracts, "Long");
            }
            else if (Close[0] < Open[0])
            {
                double stop = RoundToTick(High[0]);
                double target = RoundToTick(Close[0] - RMultiple * (High[0] - Close[0]));
                int contracts = Contracts;
                if (RiskPerTrade > 0 && stop - Close[0] > 0)
                    contracts = Math.Max(1, (int)Math.Min(Math.Floor(RiskPerTrade / ((stop - Close[0]) * pointValue)), MaxContracts));
                SetStopLoss("Short", CalculationMode.Price, stop, false);
                SetProfitTarget("Short", CalculationMode.Price, target);
                EnterShort(contracts, "Short");
            }
        }

        private double RoundToTick(double price)
        {
            return Math.Sign(price) * Math.Floor(Math.Abs(price) / TickSize + 0.5 + 1e-9) * TickSize;
        }

        #region Properties
        [NinjaScriptProperty]
        [Range(0.01, double.MaxValue)]
        [Display(Name = "Target (R)", Description = "Profit target as a multiple of the distance from the close to the stop", Order = 1, GroupName = "Parameters")]
        public double RMultiple { get; set; }

        [NinjaScriptProperty]
        [Range(0, int.MaxValue)]
        [Display(Name = "Minimum range (ticks)", Description = "Skip sessions whose first bar has a smaller range", Order = 2, GroupName = "Parameters")]
        public int MinRangeTicks { get; set; }

        [NinjaScriptProperty]
        [Range(1, int.MaxValue)]
        [Display(Name = "Contracts", Description = "Contracts per trade when RiskPerTrade is 0", Order = 3, GroupName = "Parameters")]
        public int Contracts { get; set; }

        [NinjaScriptProperty]
        [Range(0, double.MaxValue)]
        [Display(Name = "Risk per trade", Description = "Currency at risk at the stop (0: fixed contracts)", Order = 4, GroupName = "Parameters")]
        public double RiskPerTrade { get; set; }
        #endregion
    }
}
