// BtRsi2MeanReversion: generated by backtest_engine.ninjatrader (https://github.com/paolo993788/Algorithmic-trading).
// Do not edit by hand: regenerate with `python -m backtest_engine.ninjatrader --write scripts/ninjatrader_strategies`.
//
// RSI(2) mean reversion (Connors and Alvarez): buy at the next open when the close is above its TrendPeriod average and
// RSI(RsiPeriod) is below EntryLevel; exit at the next open once the close is above its ExitPeriod average; optional mirror
// image on the short side.
// The rules and defaults are those of backtest_engine.bars.rsi2_plan; the platform's historical fills
// (Calculate.OnBarClose, Standard order fill resolution, entry orders alive for one bar, TimeInForce Gtc) follow the
// model of cpp/bars.hpp, so the trade list of the Strategy Analyzer can be reconciled with the Python backtest by
// backtest_engine.ninjatrader.reconcile_trades. Apply a commission template to the backtest account: commissions are
// not a strategy property. Prices are rounded to the tick grid half away from zero, as in Python.
#region Using declarations
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Xml.Serialization;
using NinjaTrader.Cbi;
using NinjaTrader.Data;
using NinjaTrader.NinjaScript;
using NinjaTrader.NinjaScript.Indicators;
#endregion

namespace NinjaTrader.NinjaScript.Strategies
{
    public class BtRsi2MeanReversion : Strategy
    {
        private RSI rsi;
        private SMA trend, fast;

        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Description = "RSI(2) mean reversion above the 200-bar average (backtest_engine)";
                Name = "BtRsi2MeanReversion";
                Calculate = Calculate.OnBarClose;
                EntriesPerDirection = 1;
                EntryHandling = EntryHandling.AllEntries;
                IsExitOnSessionCloseStrategy = false;
                ExitOnSessionCloseSeconds = 30;
                IsFillLimitOnTouch = false;
                MaximumBarsLookBack = MaximumBarsLookBack.Infinite;
                OrderFillResolution = OrderFillResolution.Standard;
                Slippage = 0;

                StartBehavior = StartBehavior.WaitUntilFlat;
                TimeInForce = TimeInForce.Gtc;
                TraceOrders = false;
                RealtimeErrorHandling = RealtimeErrorHandling.StopCancelClose;
                StopTargetHandling = StopTargetHandling.PerEntryExecution;
                BarsRequiredToTrade = 200;
                IsInstantiatedOnEachOptimizationIteration = true;
                RsiPeriod = 2;
                EntryLevel = 10.0;
                ExitPeriod = 5;
                TrendPeriod = 200;
                Contracts = 1;
                AllowShort = false;
            }
            else if (State == State.Configure)
            {
                BarsRequiredToTrade = Math.Max(TrendPeriod, Math.Max(ExitPeriod, RsiPeriod));
            }
            else if (State == State.DataLoaded)
            {
                rsi = RSI(RsiPeriod, 1);
                trend = SMA(TrendPeriod);
                fast = SMA(ExitPeriod);
            }
        }

        protected override void OnBarUpdate()
        {
            if (BarsInProgress != 0 || CurrentBar < Math.Max(TrendPeriod, Math.Max(ExitPeriod, RsiPeriod)))
                return;
            double close = Close[0];
            if (Position.MarketPosition == MarketPosition.Long)
            {
                if (close > fast[0])
                    ExitLong("Long");
            }
            else if (Position.MarketPosition == MarketPosition.Short)
            {
                if (close < fast[0])
                    ExitShort("Short");
            }
            else if (close > trend[0] && rsi[0] < EntryLevel)
            {
                EnterLong(Contracts, "Long");
            }
            else if (AllowShort && close < trend[0] && rsi[0] > 100.0 - EntryLevel)
            {
                EnterShort(Contracts, "Short");
            }
        }

        #region Properties
        [NinjaScriptProperty]
        [Range(1, int.MaxValue)]
        [Display(Name = "RSI period", Description = "Bars of the RSI", Order = 1, GroupName = "Parameters")]
        public int RsiPeriod { get; set; }

        [NinjaScriptProperty]
        [Range(0, 100)]
        [Display(Name = "Entry level", Description = "Buy when RSI is below this level (sell short above 100 minus it)", Order = 2, GroupName = "Parameters")]
        public double EntryLevel { get; set; }

        [NinjaScriptProperty]
        [Range(1, int.MaxValue)]
        [Display(Name = "Exit average", Description = "Bars of the exit moving average", Order = 3, GroupName = "Parameters")]
        public int ExitPeriod { get; set; }

        [NinjaScriptProperty]
        [Range(1, int.MaxValue)]
        [Display(Name = "Trend average", Description = "Bars of the trend moving average", Order = 4, GroupName = "Parameters")]
        public int TrendPeriod { get; set; }

        [NinjaScriptProperty]
        [Range(1, int.MaxValue)]
        [Display(Name = "Contracts", Description = "Contracts per trade", Order = 5, GroupName = "Parameters")]
        public int Contracts { get; set; }

        [NinjaScriptProperty]
        [Display(Name = "Allow short", Description = "Also trade the short side below the trend average", Order = 6, GroupName = "Parameters")]
        public bool AllowShort { get; set; }
        #endregion
    }
}
