// BtTurnOfMonth: generated by backtest_engine.ninjatrader (https://github.com/paolo993788/Algorithmic-trading).
// Do not edit by hand: regenerate with `python -m backtest_engine.ninjatrader --write scripts/ninjatrader_strategies`.
//
// Turn-of-the-month seasonality (Lakonishok and Smidt, 1988): buy at the open of the DaysBefore-th weekday before the
// month end (holidays ignored; a missed entry is taken at the second bar of the new month) and sell at the open after the
// DaysAfter-th trading day of the new month. No order at the first bar of the data.
// The rules and defaults are those of backtest_engine.bars.turn_of_month_plan; the platform's historical fills
// (Calculate.OnBarClose, Standard order fill resolution, entry orders alive for one bar, TimeInForce Gtc) follow the
// model of cpp/bars.hpp, so the trade list of the Strategy Analyzer can be reconciled with the Python backtest by
// backtest_engine.ninjatrader.reconcile_trades. Apply a commission template to the backtest account: commissions are
// not a strategy property. Prices are rounded to the tick grid half away from zero, as in Python.
#region Using declarations
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Xml.Serialization;
using NinjaTrader.Cbi;
using NinjaTrader.Data;
using NinjaTrader.NinjaScript;
using NinjaTrader.NinjaScript.Indicators;
#endregion

namespace NinjaTrader.NinjaScript.Strategies
{
    public class BtTurnOfMonth : Strategy
    {
        private int barsInMonth = 0;
        private int lastMonth = -1;

        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Description = "Long over the turn of the month (backtest_engine)";
                Name = "BtTurnOfMonth";
                Calculate = Calculate.OnBarClose;
                EntriesPerDirection = 1;
                EntryHandling = EntryHandling.AllEntries;
                IsExitOnSessionCloseStrategy = false;
                ExitOnSessionCloseSeconds = 30;
                IsFillLimitOnTouch = false;
                MaximumBarsLookBack = MaximumBarsLookBack.Infinite;
                OrderFillResolution = OrderFillResolution.Standard;
                Slippage = 0;

                StartBehavior = StartBehavior.WaitUntilFlat;
                TimeInForce = TimeInForce.Gtc;
                TraceOrders = false;
                RealtimeErrorHandling = RealtimeErrorHandling.StopCancelClose;
                StopTargetHandling = StopTargetHandling.PerEntryExecution;
                BarsRequiredToTrade = 1;
                IsInstantiatedOnEachOptimizationIteration = true;
                DaysBefore = 1;
                DaysAfter = 3;
                Contracts = 1;
            }
        }

        private static DateTime NextWeekday(DateTime date)
        {
            DateTime d = date.Date.AddDays(1);
            while (d.DayOfWeek == DayOfWeek.Saturday || d.DayOfWeek == DayOfWeek.Sunday)
                d = d.AddDays(1);
            return d;
        }

        protected override void OnBarUpdate()
        {
            if (BarsInProgress != 0)
                return;
            DateTime date = Time[0].Date;
            int month = date.Year * 12 + date.Month;
            barsInMonth = month == lastMonth ? barsInMonth + 1 : 1;
            lastMonth = month;
            if (CurrentBar < 1)
                return;  // the first bar of the data: no order, and its month is not a new month

            DateTime ahead = date;
            for (int i = 0; i < DaysBefore; i++)
                ahead = NextWeekday(ahead);
            bool enter = NextWeekday(ahead).Month != date.Month && ahead.Month == date.Month;
            if (barsInMonth == 1)
                enter = true;  // entry missed because of a holiday at the month end: open at the next bar
            bool exit = barsInMonth == DaysAfter;

            if (Position.MarketPosition == MarketPosition.Long)
            {
                if (exit)
                    ExitLong("Long");
            }
            else if (enter && !exit)
            {
                EnterLong(Contracts, "Long");
            }
        }

        #region Properties
        [NinjaScriptProperty]
        [Range(0, 10)]
        [Display(Name = "Days before", Description = "Weekdays before the month end at whose open the position is bought", Order = 1, GroupName = "Parameters")]
        public int DaysBefore { get; set; }

        [NinjaScriptProperty]
        [Range(1, 10)]
        [Display(Name = "Days after", Description = "Trading days of the new month after which the position is sold", Order = 2, GroupName = "Parameters")]
        public int DaysAfter { get; set; }

        [NinjaScriptProperty]
        [Range(1, int.MaxValue)]
        [Display(Name = "Contracts", Description = "Contracts per trade", Order = 3, GroupName = "Parameters")]
        public int Contracts { get; set; }
        #endregion
    }
}
